ooTester/ooTester/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('task/',include('task.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ooTester/task/urls.py
from django.urls import path
from . import views

app_name = "task"
urlpatterns=[
    path('',views.showMenu,name='menu'),
    path('<int:question_id>/',views.showQuestion,name='quest'),
    path('<int:id>',views.changeValue,name='change'),
    path('reset/',views.resetQuestion,name='reset'),
    path('user/',views.getUser,name='user'),
]

ooTester/task/models.py
from django.db import models
from django import forms
from django.forms import ModelForm, NumberInput,TextInput

# Create your models here.
class Question(models.Model):
    text = models.CharField(max_length=250)
    photo = models.ImageField(upload_to='images/',null=True)
    is_complete = models.BooleanField(null=True)

    def __str__(self):
        return self.text

class UserDB(models.Model):
    name = models.CharField(max_length=100,null=True)
    age  = models.IntegerField(null=True)

    def __str__(self):
        return self.name

class User(forms.Form):
    name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'name':'username','placeholder':'Your Name ','style':'width: 300px','class':'form-control'}))
    age = forms.IntegerField(label="Your Age",min_value=6,widget=forms.NumberInput(attrs={'name':'age','placeholder':'Your Age ','style':'width: 300px','class':'form-control'}))

ooTester/task/views.py
from django.shortcuts import render
from . import models
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def showMenu(request):
    question = models.Question.objects.all()
    return render(request,'task/menu.html',{
    'question':question,
    })

def showQuestion(request, question_id):
    question = models.Question.objects.get(pk=question_id)
    return render(request,'task/question.html',{
        'question':question,
    })

def changeValue(request, id):
    question = models.Question.objects.get(pk=id)
    question.is_complete = True
    question.save()
    return HttpResponseRedirect(reverse('task:menu'))

def getUser(request):
    users =  models.UserDB.objects.all()
    if request.method == "POST":
        form = models.User(request.POST)
        if(form.is_valid()):
            for user in users:
                if user.name == form.name and user.age == form.age:
                    return HttpResponseRedirect(reverse('task:menu'))
    else:
        form = models.User()
    return render(request,'task/user.html',{
        'form':form
    })

def resetQuestion(request):
    question = models.Question.objects.all()
    if request.method == "POST":
        for quest in question :
            quest.is_complete = False
            quest.save();
    return HttpResponseRedirect(reverse('task:menu'))

ooTester/task/templates/task/menu.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>OOTester</title>
    <link rel="stylesheet" href="{% static 'task/menu.css' %}">
  </head>
  <body>
    <div id="banner">
      <h1>OOTester</h1>
      <div class="user-profile">
      </div>
    </div>
    <div id="quest-menu">
      <div id="container-1">
        {% for quest in question%}
        <div class="box">
          {% if quest.is_complete %}
            <div id="box-completed">
                <a href="#">{{forloop.counter}}</a>
            </div>
            {% else %}
            <div id="box-not-completed">
                <a href="{{quest.id}}/">{{forloop.counter}}</a>
            </div>
          {% endif %}
          </div>
          {% empty %}
            <h1>No Question</h1>
      {% endfor %}
      </div>
    </div>
    <div id="bottom">
      <form class="bottom-feature" action="{% url 'task:reset' %}" method="post">
        {% csrf_token %}
        <button type="submit" name="button">Reset</button>
      </form>
    </div>
  </body>
</html>

ooTester/task/templates/task/question.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'task/question.css' %}">
    <title>Question #{{question.id}}</title>
  </head>
  <body>
    <div id="box">
      <h1>{{question.text}}</h1>
      <img src="{{question.photo.url}}" alt="A photo" width="450" height="auto">

      <form action="{% url 'task:change' id=question.id %}" method="post">
        {% csrf_token %}
        <button type="submit" name="Complete" value="Complete ? ">Complete ?</button>
      </form>
    </div>
  </body>
</html>

ooTester/task/templates/task/user.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome !</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'task/user.css' %}">
  </head>
  <body>
    <div id="main">
      <h1>User Start From</h1>
      <div class="container">
        <form class="form-user" action="{% url 'task:user' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              {{form}}
            </div>
            <div class="form-group">
              <input class="btn btn-primary" type="submit" value="Submit">
          </div>
        </form>
      </div>
    </div>
  </body>
</html>